services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PORT:-8053}:80/tcp"
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./data/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - WEBPASSWORD=${PASSWORD:-changeme}
      - TZ=${TZ:-America/New_York}
    restart: unless-stopped
