services:
  homarr:
    image: ghcr.io/homarr-dev/homarr:latest
    container_name: homarr
    ports:
      - "${PORT:-7575}:7575"
    volumes:
      - ./data/configs:/appdata/configs
      - ./data/icons:/appdata/icons
      - ./data/data:/appdata/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
