services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    ports:
      - "${PORT:-3456}:3456"
    volumes:
      - ./data/files:/app/vikunja/files
      - ./data/db:/db
    environment:
      - VIKUNJA_DATABASE_TYPE=sqlite
      - VIKUNJA_DATABASE_PATH=/db/vikunja.db
      - VIKUNJA_SERVICE_PUBLICURL=http://localhost:${PORT:-3456}
    restart: unless-stopped
